### ISSUE TITLE
SimplaJs with Polymer2 won't work out of the box

### ISSUE THREAD

**Issue by contis2908** [simplajs/simpla#87]
### I'm submitting a
I am submitting a feature request regarding the implementation of Polymer version 2

### Description
I tried to set up SimplaJS with the basic Polymer 2 starter kit as well as the Polymer 2 entry application that can be both installed with the Polymer cli.
Unfortunately this is not working out of the box due to several dependency issues.

The following simpla imports require Polymer#^1.6.0.
simpla-admin#1.3.1, simpla-img#1.3.2, simpla-notify#1.0.1, simpla-styles#1.0.4, simpla-text#1.2.2, simple-button#0.2.4, simple-dropdown#0.2.2

This version of Polymer is not supporting the class based syntax which ships with Polymer 2

### Futher details
steps to reproduce problem: Install Polymer cli and one of the available Polymer packages (starter-kit or app)

### Browsers Affected

- [x ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE 11

**Comment by seaneking** [comment]
Yes, Simpla's elements are still on Polymer 1, this is a high priority issue for us, follow progress (and feel free to make PRs!) at #79

**Comment by bedeoverend** [comment]
This raises a point that might be worth considering after #79 - with ditching HTML and going completely JS we might have to look into how we can backwards support Polymer 2 ie HTML imports + ES6 classes. 

It might be that we just show people how to wrap them up, I’d rather not export HTML imports unless it’s a huge sticking point for people.

**Comment by madeleineostoja** [comment]
Well it's not like they're incompatible, it's just DX, and with Polymer 3 w/ the same workflow immanent, I wouldn't worry about it
